### ISSUE TITLE
[ Week 5 ] 5주차 워크북 미션 

### ISSUE THREAD

**Issue by alschlee** [DS-UMC-7th/UMC-7th-Tori#1]
### 🛠 Mission

JPA 이용해 Entity 설계 및 매핑 하기

### 📝 To-do

- [x] ERD에 해당하는 테이블들에 대한 엔티티 만들기
- [x] 워크북에서 다루지 않은 연관관계 매핑(양방향 포함) 적용하기
- [x] 엔티티의 칼럼에 대한 세부적인 설정 하기

### 🔍 접근 방법

x
